project:
  type: book

book:
  title: Title of the Thesis"
  author: "Sifael"
  date: "2023-01-01"
  chapters:
    - text: "Front matter"
      file: index.qmd
    - "chap01.qmd"
  sidebar:
    style: "docked"

format:
  # common:
  #   date-format: "D MMMM YYYY"
  #   number-depth: 2
  #   toc-depth: 2
  #   number-sections: true

  pdf:
    documentclass: report
    pdf-engine: pdflatex
    papersize: a4
    fontsize: 11pt
    geometry:
      - top=2.5cm
      - bottom=2.5cm
      - left=2.5cm
      - right=2.5cm
    block-headings: false
    knitr:
      opts_chunk:
        echo: false
        warning: false
        message: false
    template-partials:
      - "before-title.tex"
      - "title.tex"

# Meta data Variables
degreetype: Master of Science
institution: Constructor University
industryaffiliation: Roche Diagnostics, München, Germany
submitted: 2025
degrees: "MSc. Data Engineering, Constructor University Bremen"

csl: american-statistical-association.csl
